Make SiSRegInit & SiSSetLVDSetc args match in both headers that define them
Adds include of "sis_dac.h" to init.c to force compilers to compare the
definitions, making it obvious that sis_dac.h defined an extra argument
to SiSSetLVDSetc that the function itself didn't have, and that SiSRegInit
expected an unsigned long (in the form of SISIOADDRESS), not the unsigned
short that sis_dac.h claimed to pass it.

Found by the Parfait 1.0 bug checking tool:

Error: Function Call Mismatch
   Function call with extra args: Forward declaration of function 'SiSSetLVDSetc' does not match its definition
      Function expects 1 argument (SiS_Private*); given 2 (SiS_Private*, unsigned short)
        at line 604 of driver/xf86-video-sis/src/sis_dac.c in function 'SiS300Restore'.
          Function defined at line 1153 of driver/xf86-video-sis/src/init.c.
[repeated for each call]

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>